services:
  serpbear-app:
    image: towfiqi/serpbear
    container_name: serpbear
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - USER=${SERPBEAR_USER}
      - PASSWORD=${SERPBEAR_PASSWORD}
      - SECRET=${SERPBEAR_SECRET}
      - APIKEY=${SERPBEAR_APIKEY}
      - NEXT_PUBLIC_APP_URL=${SERPBEAR_URL}
      - PUID=1000
      - PGID=1000
    volumes:
      - ${PWD}/serpbear_appdata:/app/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - your-network # Change Value
    security_opt:
      - no-new-privileges:true
networks:
  your-network: # Change Value
    external: true