services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "127.0.0.1:4533:4533"
    restart: unless-stopped
#    environment:
      # Optional: put your config options customization here. Examples:
      # ND_LOGLEVEL: debug
    volumes:
      - "${PWD}/data:/data"
      - "/path/to/your/music/folder:/music:ro"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - your-network # Change Value
    security_opt:
      - no-new-privileges:true
networks:
    your-network: # Change Value
      external: true
